/*
 * t.java
 *
 * Created on 20 May 2001, 10:54
 */

package old;

/**
 * @author     danny
 * @created    26 May 2001
 */
public class t extends javax.swing.JDialog {

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;

  /**
   *  Creates new form t
   *
   * @param  parent  Description of Parameter
   * @param  modal   Description of Parameter
   */
  public t(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   *  This method is called from within the constructor to initialize the form.
   *  WARNING: Do NOT modify this code. The content of this method is always
   *  regenerated by the Form Editor.
   */
  private void initComponents() {
    //GEN-BEGIN:initComponents
    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();

    addWindowListener(
      new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent evt) {
          closeDialog(evt);
        }
      });

    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
    jSplitPane1.setAutoscrolls(true);
    jPanel1.setBackground(java.awt.Color.cyan);
    jSplitPane1.setLeftComponent(jPanel1);

    jPanel2.setBackground(java.awt.Color.orange);
    jSplitPane1.setRightComponent(jPanel2);

    getContentPane().add(jSplitPane1, java.awt.BorderLayout.NORTH);

    pack();
  }

  //GEN-END:initComponents

  /**
   *  Closes the dialog
   *
   * @param  evt  Description of Parameter
   */
  private void closeDialog(java.awt.event.WindowEvent evt) {
    //GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }

  //GEN-LAST:event_closeDialog

  /**
   * @param  args  the command line arguments
   */
  public static void main(String args[]) {
    new t(new javax.swing.JFrame(), true).show();
  }
  // End of variables declaration//GEN-END:variables

}
